
// Objective-C API for talking to the following Go packages
//
//	github.com/siyuan-note/siyuan-src/kernel/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Iosk_FRAMEWORK_H__
#define __Iosk_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
